### ISSUE TITLE
Is there a pdf version of this book？

### ISSUE THREAD

**Issue by A-Pai** [mhahsler/Introduction_to_Data_Mining_R_Examples#1]
Is there a pdf version of this book？

**Comment by mhahsler** [comment]
Currently, there is unfortunately no pdf available. I need to find some time to adapt the formatting so it compiles into a pdf.

**Comment by mhahsler** [comment]
I have just added a PDF version.

**Comment by A-Pai** [comment]
您的邮件我已收到  I have received your email                        李刚  LI,Gang
