### ISSUE TITLE
JOSE Submission JOSE Paper

### ISSUE THREAD

**Issue by stats-tgeorge** [mhahsler/Introduction_to_Data_Mining_R_Examples#5]
JOSE Paper Updates
- [x] Describe the submission, and explain its eligibility for JOSE.
- [x] Tell us the “story” of the project: how did it come to be?
- [x] Cite key references, including a link to the open archive of the software or the learning module. You likely need to call your .bib file.

**Comment by stats-tgeorge** [comment]
@mhahsler Can you confirm these were completed a while back?

**Comment by mhahsler** [comment]
@stats-tgeorge Yes, the paper contains the eligibility and the story in the paper section "Statement of Need." There is a link to the GitHub version of the book at the end of the summary. Please let me know if additional changes are needed.
